services:

  auth-api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    image: auth-service
    ports:
      - "5001:8080"
    env_file:
      - .env
    depends_on:
      - auth-db

  auth-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dev@123456
    ports:
      - "1434:1433"
    volumes:
      - auth_sql_data:/var/opt/mssql

volumes:
  auth_sql_data:
